variable "proxy_addr" {
  description = "Teleport proxy address of the Beams tenant."
  type        = string
  default     = "flat-pine.beams.sh:443"
}

variable "reviewer_user" {
  description = "Local Teleport user who approves change requests, holding role webmaster. Self-review is not allowed, so this must not be the requester."
  type        = string
  default     = "webmaster"
}

variable "requester_user" {
  description = "Teleport username of the change requester (you). Only used for suggested reviewers wiring and outputs; SSO users cannot have roles attached via Terraform."
  type        = string
  default     = "alex.hemard@goteleport.com"
}

variable "kube_cluster_name" {
  description = "Name of the EKS cluster, and the name it registers under in Teleport (teleport-kube-agent kubeClusterName). One name for both, since they're always the same cluster."
  type        = string
  default     = "emailpals-production"
}

variable "kube_labels" {
  description = "Teleport labels the kube agent registers with, and which the executor bot role is allowed to reach."
  type        = map(list(string))
  default     = { env = ["demo"] }
}

variable "kube_namespace" {
  description = "Kubernetes namespace the executor bot may act in."
  type        = string
  default     = "emailpals"
}

variable "kube_view_group" {
  description = "Kubernetes group for read-only access (investigator bot and the on-call operator). Bound to ClusterRole view in k8s/rbac.yaml."
  type        = string
  default     = "oncall-view"
}

variable "kube_admin_group" {
  description = "Kubernetes group for full cluster-admin access, bound to the builtin cluster-admin ClusterRole in k8s/rbac.yaml. Impersonated by the administrator Teleport role — both per-CR executor bots and the short-lived cluster-setup bot (demo/lib-teleport-admin.sh) hold it, never standing. Deliberately not attached to operator or any other standing identity."
  type        = string
  default     = "administrator"
}

variable "create_kube_join_token" {
  description = "Create a join token for the teleport-kube-agent Helm chart."
  type        = bool
  default     = true
}

variable "kube_join_token_ttl" {
  description = "Lifetime of the kube agent join token, as a Terraform duration (e.g. 24h)."
  type        = string
  default     = "24h"
}

variable "request_max_duration" {
  description = "Maximum access duration a change request may ask for."
  type        = string
  default     = "4h"
}

# ---- EKS (replaces the local kind cluster) --------------------------------
# Applying these requires AWS credentials in the environment (AWS_PROFILE,
# AWS_ACCESS_KEY_ID/SECRET, or an assumed role) separate from the Teleport
# provider's `tctl terraform env` credentials. Real billable AWS resources.

variable "teleport_creator" {
  description = "Value for the teleport.dev/creator tag applied to every AWS resource this module creates (VPC, EKS cluster, node group, ...)."
  type        = string
  default     = "alex.hemard@goteleport.com"
}

variable "aws_region" {
  description = "AWS region for the EKS cluster and its VPC."
  type        = string
  default     = "us-east-2"
}

variable "eks_kubernetes_version" {
  description = "Kubernetes version for the EKS control plane."
  type        = string
  default     = "1.31"
}

variable "vpc_cidr" {
  description = "CIDR block for the EKS cluster's VPC. Ignored when var.vpc_id is set."
  type        = string
  default     = "10.42.0.0/16"
}

variable "vpc_id" {
  description = "Reuse an existing VPC instead of creating one (e.g. the account is already at its VpcLimitExceeded quota in this region). When set, var.private_subnet_ids must also be set, and module.vpc is skipped entirely."
  type        = string
  default     = null
}

variable "private_subnet_ids" {
  description = "Private subnet IDs in the existing VPC (var.vpc_id) to run the EKS control plane ENIs and node group in. Required when var.vpc_id is set; ignored otherwise."
  type        = list(string)
  default     = null
}

variable "cluster_endpoint_public_access" {
  description = "Expose the EKS API server's control-plane endpoint on the public internet. Default false: once teleport-kube-agent is installed, Teleport (tsh kube login) is the bastion for all ongoing kubectl access and never touches this endpoint. The one-time agent install (terraform/bootstrap-kube-agent.sh, generated by terraform apply) needs network access to this endpoint before Teleport has anything to proxy — run it from AWS CloudShell launched in this VPC (see terraform/README.md) to keep this false, or set this true for that one run if CloudShell isn't an option."
  type        = bool
  default     = false
}

variable "node_instance_types" {
  description = "Instance types for the EKS managed node group."
  type        = list(string)
  default     = ["t3.medium"]
}

variable "node_desired_size" {
  description = "Desired number of nodes in the EKS managed node group. Pinned to 1: multi-node spreads the teleport-kube-agent pod away from app pods it needs to reach (emailpals-web etc.), and the node security group has no rule permitting that cross-node pod traffic."
  type        = number
  default     = 1
}

variable "node_min_size" {
  description = "Minimum number of nodes in the EKS managed node group."
  type        = number
  default     = 1
}

variable "node_max_size" {
  description = "Maximum number of nodes in the EKS managed node group. Pinned to 1, see node_desired_size."
  type        = number
  default     = 1
}
